### ISSUE TITLE
Pick a single SBOM format to support?

### ISSUE THREAD

**Issue by tofay** [alilleybrinker/cargo-spdx#7]
[4.4 of the SPDX spec](https://spdx.github.io/spdx-spec/conformance/) says :

```
Interoperability between all the supported file formats shall be preserved. SPDX defines how to validate a document in
each supported format, and how to translate a valid document without loss to each other supported format.
```

Does `cargo-spdx` need to be able to generate tag value format SBOMs? Can we initially just always output JSON SBOMs and assume that downstream tooling can handle JSON.

The tag value format doesn't have a deserializer in Rust, so continuing with this means cargo-spdx needs to write one, which will slow down development compared to if we just focus on one of the other formats. For these we can generate Rust structs from the schema and use serde for deserialization - that would narrow it down to json/yaml.

**Comment by alilleybrinker** [comment]
Hmm... the intent on my part had been to support as many of the formats as possible (you beat me to the punch on JSON and YAML!). You're right that there's not a deserializer already built for the tag-value format, but I would consider tag-value format support to be part of the minimum viable product. I'm happy to work on it myself. It's a nice human readable format, and it's what a lot of the sample SPDX materials are based on right now.

**Comment by tofay** [comment]
Re potential upstreaming to cargo, I suspect cargo team would prefer to output just JSON, to avoid taking dependencies on another serialization format with potentially less hardened libraries such as SPDX tag/value or yaml. I can ask on zulip.

**Comment by alilleybrinker** [comment]
Yeah, I'd appreciate the input of the Cargo team. Thanks!

**Comment by tofay** [comment]
Per the discussion on zulip, I'll close this. If folk need a certain output format they can add support for it.
